### ISSUE TITLE
`pthread_join` causing segmentation fault in `executeQuery()`

### ISSUE THREAD

**Issue by smburdick** [Puget-Sound-Bitmaps/bitmap-engine#12]
I believe this may be due to the way `pthread_create()` is being called, see https://stackoverflow.com/questions/20200622/segmentation-fault-at-pthread-join. Investigating this one now.

**Comment by Jahrme** [comment]
I was just looking at ` Query.c` and my testing seems to indicate that the error is a result of [this](https://github.com/Jahrme/Bitmap-Engine/blob/f6b329a7bdd1b316e9a1c9f6240166b3e923a91a/BitmapEngine/src/query/Query.c#L270) memory allocation.

When running the test code, `sz` had a value of `-706` which causes a **huge** memory allocation because `malloc` interprets negative numbers as an unsigned value (see [here](https://stackoverflow.com/questions/17925771/what-happens-when-we-call-malloc-with-negative-parameter)). Thus, the testing code is trying to allocate on the order of `16 EiB` of memory which (obviously) fails.

Thus, `*ret` receives `NULL` which results in `ret[0]` causing a segmentation fault.
