### ISSUE TITLE
Format of stored bitmap files

### ISSUE THREAD

**Issue by smburdick** [Puget-Sound-Bitmaps/bitmap-engine#15]
## Master
We could do something like `[vec_id] [vec] [m1] [m2] [...] [mn]`, where the `m`s are the identifiers of machines that have the vector.
```
1 0x00 1 2 3
2 0x01 2 3 4
```
## Slave
Just id and compressed vector.
```
1 0x00
2 0x01
[...]
```

**Comment by Jahrme** [comment]
In order to not have to store the machine identifiers, we could do the following:
- given a replication factor `r`,
- given a vector identifier `n`,
- given a vector `V`,
- the master node's identifier(s) for `V` will correspond to `n' in range(n * r, n * r + r)`.

Thus, given a replication factor of `3`, if the DBMS sends the master node:
```
0 0xA7
1 0x4C
[. . .]
```
The master node will (internally) work with:
```
0 0xA7
1 0xA7
2 0xA7
3 0x4C
4 0x4C
5 0x4C
[. . .]
```

**Comment by smburdick** [comment]
The way I'd write the range of identifiers:
`{m | nr <= m < r(n+1) }`

**Comment by Jahrme** [comment]
Given an internal identifier `n`, the DBMS's identifier can be recovered by calculating `n // r` (where `//` corresponds to integer division).

**Comment by smburdick** [comment]
However if replication factor changed, or if one vector was to be replicated more, then every vector would have to be remapped as we'd have stale data.

**Comment by smburdick** [comment]
Also, if during a two-phase commit, one of the intended recipients of a bit vector crashes, should we just only commit the vector to the machines that didn't crash, or find a new one? If we did the latter, then this scheme would be inconsistent.
